<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="192.168.1.15" failures="4" tests="31" name="/Users/uroskatanic/IdeaProjects/REST-Assured-Framework" time="12.433" errors="0" timestamp="2023-06-17T15:15:29 CEST">
  <testcase classname="tests.test_for_books.add_book_store" name="BookStore_AddBook_ID" time="0.638">
    <failure type="java.lang.AssertionError" message="Wrong status code expected200 received500">
      <![CDATA[java.lang.AssertionError: Wrong status code expected200 received500
at org.testng.Assert.fail(Assert.java:110)
at requests.POST_Request.POSTRequest(POST_Request.java:87)
at tests.test_for_books.add_book_store.BookStore_AddBook_ID(add_book_store.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- BookStore_AddBook_ID -->
  <testcase classname="tests.test_for_books.add_book_store" name="BookStore_AddBook_Msg" time="0.52">
    <failure type="java.lang.AssertionError" message="Wrong status code expected200 received500">
      <![CDATA[java.lang.AssertionError: Wrong status code expected200 received500
at org.testng.Assert.fail(Assert.java:110)
at requests.POST_Request.POSTRequest(POST_Request.java:87)
at tests.test_for_books.add_book_store.BookStore_AddBook_Msg(add_book_store.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- BookStore_AddBook_Msg -->
  <testcase classname="tests.test_for_books.add_book_store" name="BookStore_AddBook_Status" time="0.526">
    <failure type="java.lang.AssertionError" message="Wrong status code expected200 received500">
      <![CDATA[java.lang.AssertionError: Wrong status code expected200 received500
at org.testng.Assert.fail(Assert.java:110)
at requests.POST_Request.POSTRequest(POST_Request.java:87)
at tests.test_for_books.add_book_store.BookStore_AddBook_Status(add_book_store.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- BookStore_AddBook_Status -->
  <testcase classname="tests.test_for_books.add_book_store" name="Existing_book" time="0.516">
    <failure type="java.lang.AssertionError" message="Wrong status code expected404 received500">
      <![CDATA[java.lang.AssertionError: Wrong status code expected404 received500
at org.testng.Assert.fail(Assert.java:110)
at requests.POST_Request.POSTRequest(POST_Request.java:87)
at tests.test_for_books.add_book_store.Existing_book(add_book_store.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- Existing_book -->
  <testcase classname="tests.test_for_books.checkMultyBooks" name="checkBookID" time="0.543"/>
  <testcase classname="tests.test_for_books.checkMultyBooks" name="checkBookID" time="0.3"/>
  <testcase classname="tests.test_for_books.checkMultyBooks" name="checkBookID" time="0.302"/>
  <testcase classname="tests.test_for_books.checkMultyBooks" name="checkBookID" time="0.302"/>
  <testcase classname="tests.test_for_books.checkMultyBooks" name="checkBookID" time="0.301"/>
  <testcase classname="tests.test_for_books.checkMultyBooks" name="checkBookID" time="0.29"/>
  <testcase classname="tests.test_for_books.checkMultyBooks" name="checkBookID" time="0.31"/>
  <testcase classname="tests.test_for_books.checkMultyBooks" name="incorrect_Books" time="0.296"/>
  <testcase classname="tests.test_for_books.checkMultyBooks" name="incorrect_Books" time="0.284"/>
  <testcase classname="tests.test_for_books.checkMultyBooks" name="incorrect_Books" time="0.296"/>
  <testcase classname="tests.test_for_books.checkMultyBooks" name="incorrect_Books" time="0.308"/>
  <testcase classname="tests.fake_google_maps_api.get_data_for_place" name="TestCase01_Get_Data_for_Place" time="0.361"/>
  <testcase classname="tests.fake_google_maps_api.get_data_for_place" name="TestCase02_Check_Name" time="0.354"/>
  <testcase classname="tests.fake_google_maps_api.get_data_for_place" name="testCase03_PlaceID_New" time="0.348"/>
  <testcase classname="tests.fake_google_maps_api.get_data_for_place" name="testCase04_Check_address" time="0.354"/>
  <testcase classname="tests.fake_google_maps_api.get_data_for_place" name="testCase05_Check_types" time="0.356"/>
  <testcase classname="tests.fake_google_maps_api.get_data_for_place" name="testCase06_Check_language" time="0.348"/>
  <testcase classname="tests.fake_google_maps_api.get_data_for_place" name="testCase07_Check_website" time="0.416"/>
  <testcase classname="tests.fake_google_maps_api.get_data_for_place" name="testCase08_Ceheck_body" time="0.0"/>
  <testcase classname="tests.fake_google_maps_api.create_place" name="TestCase01" time="1.004"/>
  <testcase classname="tests.fake_google_maps_api.create_place" name="TestCase02" time="0.375"/>
  <testcase classname="tests.fake_google_maps_api.create_place" name="TestCase03" time="0.336"/>
  <testcase classname="tests.fake_google_maps_api.delete_place" name="testCase01DeleteJustCreatedPlace" time="0.568"/>
  <testcase classname="tests.fake_google_maps_api.delete_place" name="testCase02DeleteNotExistingPlaceID" time="0.541"/>
  <testcase classname="tests.fake_google_maps_api.update_place" name="TestCase03" time="0.366"/>
  <testcase classname="tests.fake_google_maps_api.get_data_for_place_POJO" name="get_data" time="0.382"/>
  <testcase classname="tests.Google_Maps_POJO.first_test" name="testCase" time="0.545"/>
</testsuite> <!-- /Users/uroskatanic/IdeaProjects/REST-Assured-Framework -->
